conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
]

core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name = 'core/login.html' ,authentication_form = LoginForm), name='login'),

]

dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
]

iiti_olx/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path , include


urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
    path('admin/', admin.site.urls),
    path("accounts/", include("allauth.urls")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

item/urls.py
from django.urls import path 

from . import views

app_name = 'item'

urlpatterns = [
    path('' , views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),    

]

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your Username',
        'class': 'w-full py-4 px-6 rounded-xl'
        }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
        }))
    
    
class SignUpForm(UserCreationForm):
    
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', )


    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your Username',
        'class': 'w-full py-4 px-6 rounded-xl'
        }))
    
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email address',
        'class': 'w-full py-4 px-6 rounded-xl'
        }))
    
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
        }))
    
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': 'w-full py-4 px-6 rounded-xl'
        }))

core/views.py
from django.shortcuts import render, redirect

from item.models import Category, Item

from .forms import SignUpForm
# Create your views here.
from django.db.models import Q

def index(request):
    query = request.GET.get('query', '')
    item_queryset = Item.objects.filter(is_sold=False)

    if query:
        item_queryset = item_queryset.filter(
            Q(name__icontains=query) | Q(description__icontains=query)
        )

    items = item_queryset[:8]
    categories = Category.objects.all()

    return render(request, 'core/index.html', {
        'categories': categories,
        'items': items,
        'query': query,
    })


def contact(request):
    return render(request, 'core/contact.html')


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login/')

    else:
        form = SignUpForm()

    return render(request, 'core/signup.html', {
        'form': form,
    })

core/templates/core/base.html
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <script src="https://cdn.tailwindcss.com"></script>

        <title>{% block title %}{% endblock %} | IITI OLX</title>

    </head>

    <body>
        
        <nav class="flex items-center justify-between flex-wrap bg-teal-300 p-6">
            <div class="flex items-center flex-shrink-0 mr-6">
                <a href="/" class="font-bold text-xl tracking-tight">IITI OLX</a>
            </div>
            <div class="block lg:hidden">
                <button class="flex items-center px-3 py-2 border rounded text-teal-200 border-teal-400 hover:text-white hover:border-white">
                    <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
                </button>
            </div>
            <div class="menu hidden w-full block flex-grow lg:flex lg:items-center lg:w-auto">
                <div class="text-sm lg:flex-grow">
                    <a href="{% url 'item:new' %}" class="block mt-4 lg:inline-block lg:mt-0 text-gray-800 hover:text-gray-900 mr-4">
                        New Item
                    </a>
                    <a href="{% url 'item:items' %}" class="block mt-4 lg:inline-block lg:mt-0 text-gray-800 hover:text-gray-900 mr-4">
                        Browse
                    </a>
                </div>
                <div>
                    {% if request.user.is_authenticated %}
                    <a href="{% url 'conversation:inbox' %}" class="inline-block px-4 py-2 text-sm font-medium text-gray-900 bg-gray-200 rounded-md hover:bg-gray-300 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500 mt-4 lg:mt-0 mr-4">
                        Inbox
                    </a>
                    <a href="{% url 'dashboard:index' %}" class="inline-block px-4 py-2 text-sm font-medium text-gray-900 bg-gray-200 rounded-md hover:bg-gray-300 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500 mt-4 lg:mt-0">
                        Dashboard
                    </a>
                    {% else %}
                    <a href="{% url 'core:signup' %}" class="inline-block px-4 py-2 text-sm font-medium text-gray-900 bg-gray-200 rounded-md hover:bg-gray-300 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500 mt-4 lg:mt-0 mr-4">
                        Sign Up
                    </a>
                    <a href="{% url 'core:login' %}" class="inline-block px-4 py-2 text-sm font-medium text-gray-900 bg-gray-200 rounded-md hover:bg-gray-300 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500 mt-4 lg:mt-0">
                        Log In
                    </a>
                    {% endif %}
                </div>
            </div>
              
        </nav>
          
          

        <div class="px-6 py-6">
            {% block content %}
            {% endblock %}
        </div>

        <footer class="py-6 px-6 flex justify-between bg-gray-800">
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-semibold text-gray-400">About</h3>

                <p class="text-lg text-gray-300">Open platform to buy and sell!!</p>
            </div>

            <div class="w-1/3">
                <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>

                <ul class="space-y-2">
                    <li><a href="#" class="text-lg text-teal-300 hover:text-teal-500">About</a></li>
                    <li><a href="{% url 'core:contact' %}" class="text-lg text-teal-300 hover:text-teal-500">Contact</a></li>
                    <li><a href="#" class="text-lg text-teal-300 hover:text-teal-500">Privacy policy</a></li>
                    <li><a href="#" class="text-lg text-teal-300 hover:text-teal-500">Terms of use</a></li>

                </ul>
            </div>

        </footer>
        
        <script>
            const button = document.querySelector('button');
            const menu = document.querySelector('.menu');
          
            button.addEventListener('click', () => {
              menu.classList.toggle('hidden');
            });
        </script>
          
    </body>
        
</html>

core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %}Contact{% endblock %}

{% block content %}
    <h1>Contact page</h1>
{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Home{% endblock %}

{% block content %}

    <div class="px-6 py-4 bg-gray-100 rounded-xl">

        <form action="{% url 'item:items' %}" method="get">
            <div class="flex mb-6">
              <input type="text" name="query" class="w-full py-4 px-6 border rounded-xl" value="{{ query }}" placeholder="Find a phone, clothes...">
              <button class="ml-2 py-4 px-8 text-lg bg-teal-500 text-white rounded-xl">Search</button>
            </div>
        </form>

        <h2 class="mb-12 text-2xl text-center">Newest items</h2>

        <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3">
            {% for item in items %}
                <div>
                    <a href="{% url 'item:detail' item.id %}">
                        <div>
                            <img src="{{ item.image.url }}" class="rounded-t-xl w-full object-cover md:h-48">
                        </div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h3 class="text-2xl font-semibold">{{ item.name }}</h3>
                            <p class="text-gray-500">Price: ₹{{ item.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Categories</h2>

        <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3">
            {% for category in categories %}
                <div>
                    <a href="#">
                        <div class="p-6 bg-white rounded-b-xl">
                            <h3 class="text-2xl font-semibold">{{ category.name }}</h3>
                            <p class="text-gray-500">{{ category.items.count }} items</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Log In{% endblock %}

{% block content %}

{% load socialaccount %}

<div class="w-full md:w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl text-center">Log In</h1>

    <form action="." method="post">
        {% csrf_token %}

        <div class="mb-3">
            <label class="block mb-2">Username</label>
            {{ form.username }}
        </div>

        <div class="mb-6">
            <label class="block mb-2">Password</label>
            {{ form.password }}
        </div>


        {% if form.errors or form.non_field_errors %}
            <div class="mb-6 p-4 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}


            </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white w-full">Submit</button>
        
        <div class="text-center">
            <a href="{% provider_login_url 'google' %}?next=/"
                class="inline-block px-3 py-2 text-sm leading-none text-white bg-red-500 hover:bg-red-700 rounded-lg font-bold mt-6">
                <span class="flex items-center">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="20" height="20" class="mr-2">
                        <path fill="#ffffff" d="M22.64 11.33c0-.78-.07-1.56-.22-2.32H12v4.42h6.1c-.26 1.35-.95 2.48-1.99 3.24v2.67h3.22c1.88-1.73 2.98-4.27 2.98-7.01z"/>
                        <path fill="#ffffff" d="M12 21c2.7 0 4.96-.9 6.6-2.45l-3.22-2.67c-.88.66-2 1.07-3.38 1.07-2.6 0-4.8-1.76-5.59-4.13H2.36v2.59A9.996 9.996 0 0 0 12 21z"/>
                        <path fill="#ffffff" d="M6.41 13.16c-.24-.7-.37-1.44-.37-2.2s.13-1.5.37-2.2V6.38H2.36a9.946 9.946 0 0 0 0 11.25l4.05-3.47z"/>
                        <path fill="#ffffff" d="M12 3.91c1.4 0 2.68.48 3.68 1.43l2.75-2.75C16.92.93 14.66 0 12 0 6.47 0 2 4.47 2 10s4.47 10 10 10c3.48 0 6.59-1.75 8.44-4.41l-2.83-2.12c-1.13 1.4-2.89 2.3-4.88 2.3-3.31 0-6-2.69-6-6s2.69-6 6-6z"/>
                    </svg>
                    Sign Up with Google
                </span>
            </a>
        </div>
        
    </form>
</div>
{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}

{% load socialaccount %}
    
<div class="w-full lg:w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl text-center">Sign Up</h1>

    <form action="." method="post">
        {% csrf_token %}

        <div class="mb-6">
            <label class="block mb-2">Username</label>
            {{ form.username }}
        </div>

        <div class="mb-6">
            <label class="block mb-2">Email</label>
            {{ form.email }}
        </div>

        <div class="mb-6">
            <label class="block mb-2">Password</label>
            {{ form.password1 }}
        </div>

        <div class="mb-6">
            <label class="block mb-2">Repeat Password</label>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-6 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="block w-full py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
        
        
        <div class="text-center">
            <a href="{% provider_login_url 'google' %}?next=/"
                class="inline-block px-3 py-2 text-sm leading-none text-white bg-red-500 hover:bg-red-700 rounded-lg font-bold mt-6">
                <span class="flex items-center">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="20" height="20" class="mr-2">
                        <path fill="#ffffff" d="M22.64 11.33c0-.78-.07-1.56-.22-2.32H12v4.42h6.1c-.26 1.35-.95 2.48-1.99 3.24v2.67h3.22c1.88-1.73 2.98-4.27 2.98-7.01z"/>
                        <path fill="#ffffff" d="M12 21c2.7 0 4.96-.9 6.6-2.45l-3.22-2.67c-.88.66-2 1.07-3.38 1.07-2.6 0-4.8-1.76-5.59-4.13H2.36v2.59A9.996 9.996 0 0 0 12 21z"/>
                        <path fill="#ffffff" d="M6.41 13.16c-.24-.7-.37-1.44-.37-2.2s.13-1.5.37-2.2V6.38H2.36a9.946 9.946 0 0 0 0 11.25l4.05-3.47z"/>
                        <path fill="#ffffff" d="M12 3.91c1.4 0 2.68.48 3.68 1.43l2.75-2.75C16.92.93 14.66 0 12 0 6.47 0 2 4.47 2 10s4.47 10 10 10c3.48 0 6.59-1.75 8.44-4.41l-2.83-2.12c-1.13 1.4-2.89 2.3-4.88 2.3-3.31 0-6-2.69-6-6s2.69-6 6-6z"/>
                    </svg>
                    Sign Up with Google
                </span>
            </a>
        </div>
        


    </form>
</div>
{% endblock %}